name: 🐞 Bug Report
description: 버그 발생 시 작성하는 이슈입니다.
title: "[Bug] "
labels: ["🐞 Bug"]

body:
  - type: textarea
    id: bug-summary
    attributes:
      label: "#️⃣ 버그 발생 관련"
      description: 어떤 버그인지 간결하게 설명해주세요.
    validations:
      required: true

  - type: textarea
    id: bug-details
    attributes:
      label: "#️⃣ 버그 발생 상세 설명"
      description: 가능한 경우 Given-When-Then 형식으로 서술해주세요.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "#️⃣ 예상 결과 (expected)"
      description: 정상적인 기대 결과를 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "#️⃣ 실제 결과 (actual)"
      description: 실제로 어떤 결과가 발생했는지 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: timetable
    attributes:
      label: "#️⃣ 타임 테이블"
      description: 진행상황 타임테이블을 작성해주세요.
      value: |
        |시간|세부내용|담당자|
        |:---:|:---|:---:|
        |00:00|내용|이름|
        |00:00|내용|이름|
        |00:00|내용|이름|
        |00:00|내용|이름|
        |00:00|내용|이름|

  - type: textarea
    id: references
    attributes:
      label: "📎 참고 자료(선택)"
      description: 참고할 자료가 있다면 작성해주세요 (링크, 스크린샷 등)
