name: ✨ Feature Request
description: 신규 기능 개발 시 작성하는 이슈입니다.
title: "[Feature] "
labels: ["✨ Feature"]

body:
  - type: textarea
    id: description
    attributes:
      label: "📝 Description"
      description: 기능 개요와 목적을 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: "🎯 Goals"
      description: 이 기능을 통해 달성하고자 하는 목표를 작성해주세요.
      value: |
        - [ ] 목표 1
        - [ ] 목표 2
        - [ ] 목표 3
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: "🔗 Related Issues"
      description: 연관된 이슈를 연결해주세요. 예: `- #12`
  
  - type: input
    id: deadline
    attributes:
      label: "🗓️ Deadline / Priority"
      description: 목표 완료일을 작성해주세요. 예: `YYYY-MM-DD`
